server:
  # 该服务的端口号
  port: 9002

spring:
  application:
    #注册到注册中心的名称,注意不能使用“_”
    name: fishServiceApi

apollo:
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true
    namespaces: fishServiceApi,application