server:
  #服务端口
  port: 8901
spring:
  application:
    name:
      spring-cloud-eureka-8901


apollo:
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true
    namespaces: fishEureka,application
