server:
  #服务端口
  port: 8900


spring:
  application:
    name:
      spring-cloud-eureka-8900

apollo:
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true
    namespaces: fishEureka,application

