server:
  # 该服务的端口号
  port: 9101

spring:
  application:
    #注册到注册中心的名称,注意不能使用“_”
    name: fishBaseService-9101

apollo:
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true
    namespaces: fishBaseService,application
  configService:
  access-key:
    secret:

