on:
  push:
    branches:
      - master  # 监听推送到 master 分支的变化

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        module:
          - fish-gateway
          - fish-auth-service
          - fish-base-service
          - fish-eureka
          - fish-service-api

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Install parent project
        run: |
          mvn clean install -DskipTests  # 构建根目录的 pom.xml，安装所有模块

      - name: Build Docker Images and Push
        run: |
          # 为每个模块构建并推送 Docker 镜像
          cd ${{ matrix.module }}
          docker build -t hollow288/${{ matrix.module }}:latest .  # 构建镜像
          docker push hollow288/${{ matrix.module }}:latest  # 推送镜像
